(* "Load HEARTS + EXPERT (dev builds) on LOOPS and check the KB wiring.  Run with --loops.")
(LOAD "{DSK}/hearts/medley/HEARTS")
(LOAD "{DSK}/hearts/medley/EXPERT")
(HT.CHECK "expert.players unit" (GetObjectRec (QUOTE expert.players)))
(HT.CHECK "strategy units" (AND (GetObjectRec (QUOTE Minimizing)) (GetObjectRec (QUOTE Shooting)) (GetObjectRec (QUOTE Eclipsing))))
(HT.CHECK "16 rule classes" (LENGTH KEE.RuleClasses) 16)
(HT.CHECK "follow.play has 12 rules" (LENGTH (KEE.RulesOf (QUOTE follow.play))) 12)
(HT.CHECK "rules sorted by weight" (for C in KEE.RuleClasses always (for R on (CDR C) always (OR (NULL (CDR R)) (GEQ (CADR (CAR R)) (CADR (CADR R)))))))
(SETQ P (H.MakePlayer (QUOTE EP) NIL))
(HT.CHECK "player record is Kee" (fetch Type of P) (QUOTE Kee))
(SETQ U (fetch Object of P))
(HT.CHECK "history unit" (GET.VALUE U (QUOTE history)))
(HT.CHECK "personality via default" (KEE.TheValue (QUOTE TriggerHappiness) (GET.VALUE U (QUOTE Personality))) 0.5)
(UNIT.NAME U)
(SETQ H (Hand.Create (HP.ChooseSomeCards 13 (HP.MakeDeck))))
(H.Apply P (QUOTE GiveHand) H 1)
(HT.CHECK "13 cards" (LENGTH (Hand.Cards (GET.VALUE U (QUOTE Hand)))) 13)
(HT.CHECK "39 cards left not counting mine" (LENGTH (GET.VALUES (GET.VALUE U (QUOTE history)) (QUOTE CardsLeft))) 52)
(SETQ KEE.Trace T)
(SETQ PASSED (H.Apply P (QUOTE PassOut) (QUOTE Left)))
(HT.CHECK "passes 3 cards" (LENGTH PASSED) 3)
(GET.VALUE U (QUOTE Strategy))
KEE.Fired
KEE.RuleErrors
(H.Apply P (QUOTE PassIn) (LIST (Card.Create 2 (QUOTE H)) (Card.Create 3 (QUOTE H)) (Card.Create 4 (QUOTE C))))
(GET.VALUE U (QUOTE Strategy))
(KEE.CF.Get (GET.VALUE U (QUOTE RightPlayer)) (QUOTE Strategy) (QUOTE Shooting))
(KEE.CF.Get (GET.VALUE U (QUOTE RightPlayer)) (QUOTE Strategy) (QUOTE Minimizing))
KEE.Fired
KEE.RuleErrors
