(* "Soak test: several complete games, mostly all-Expert, to shake out rare situations.
    Run with --loops and a long --timeout.  A hang (break window) shows up as timeout.png.")
(LOAD "{DSK}/hearts/medley/HEARTS")
(LOAD "{DSK}/hearts/medley/EXPERT")
(HT.AUTOPLACE)
(SETQ ThinkFlag? NIL)
(DEFINEQ
(EPT.CheckPlay (LAMBDA (self Card)
  (SETQ EPT.Plays (ADD1 EPT.Plays))
  (if (NOT (CardList.Member Card (GET.VALUE self (QUOTE LegalCards))))
      then (push EPT.Illegal (LIST (UNIT.NAME self) Card (GET.VALUE self (QUOTE LatestReason)))))
  Card))
(EPT.Game (LAMBDA (Config)
  (Hearts (for X in Config collect (H.MakePlayer X NIL)) NIL NIL)
  (LIST (LENGTH (fetch Deals of H.LastGame)) (fetch Score of H.LastGame))))
)
(SETQ EPT.Illegal NIL)
(SETQ EPT.Plays 0)
(ADVISE (QUOTE EP.Play) (QUOTE AFTER) (QUOTE (EPT.CheckPlay self !VALUE)))
(SETQ KEE.RuleErrors NIL)
(EPT.Game (QUOTE (EP EP EP EP)))
(EPT.Game (QUOTE (EP EP CP CLOWN)))
(EPT.Game (QUOTE (EP EP EP EP)))
(HT.CHECK "every Expert play legal" (NULL EPT.Illegal))
EPT.Plays
(HT.CHECK "no rule errors" (NULL KEE.RuleErrors))
(for E in KEE.RuleErrors bind Seen unless (MEMBER (CAR E) Seen) collect (PROGN (push Seen (CAR E)) E))
