(* "Does LOOPS load and work headlessly?  Run with --loops.")
(HT.CHECK "LOOPS functions defined" (AND (GETD (QUOTE DefineClass)) (GETD (QUOTE GetValue))))
(DefineClass (QUOTE HTTestClass) (QUOTE (Object)))
(_ ($ HTTestClass) AddIV (QUOTE Color) (QUOTE red))
(SETQ HTObj (_ ($ HTTestClass) New))
(HT.CHECK "GetValue default" (GetValue HTObj (QUOTE Color)) (QUOTE red))
(PutValue HTObj (QUOTE Color) (QUOTE blue))
(HT.CHECK "PutValue/GetValue" (GetValue HTObj (QUOTE Color)) (QUOTE blue))
(HT.SNAP "loops")
