(* "PLAYHEARTS: the menu-driven front door.  Session set-up, Start Game, a second game on a
    fresh table, Exit mid-game (process stopped, windows closed, Expert units deleted).
    Run with --loops.")
(LOAD "{DSK}/hearts/medley/HEARTS")
(LOAD "{DSK}/hearts/medley/EXPERT")
(LOAD "{DSK}/hearts/dist/PLAYHEARTS")
(HT.AUTOPLACE)
(SETQ ThinkFlag? T)
(SETQ Game.OverScore 20)
(DEFINEQ (PHT.Wait (LAMBDA (Table Secs)
  (for I from 1 to (TIMES 2 Secs) while (PH.Running? Table) do (DISMISS 500))
  (NOT (PH.Running? Table))))
 (PHT.HeartsWindows (LAMBDA NIL
  (for W in (OPENWINDOWS) when (PH.HeartsWindow? W) collect (WINDOWPROP W (QUOTE TITLE))))))
(SETQ T1 (PlayHearts (QUOTE (EP CP CLOWN EP))))
(HT.CHECK "table is open" (OPENWP T1))
(HT.CHECK "table has the menu bar" (ATTACHEDWINDOWS T1))
(HT.CHECK "nothing plays before Start Game" (NULL (PH.Running? T1)))
(SETQ NAME1 (UNIT.NAME (fetch Object of (CAR (WINDOWPROP T1 (QUOTE PH.Players))))))
(HT.CHECK "Start Game starts a game process" (PH.Start T1))
(HT.CHECK "Start Game again while playing is refused" (NULL (PH.Start T1)))
(HT.CHECK "game 1 finishes" (PHT.Wait T1 600))
(HT.CHECK "game 1 has a winner" (fetch Winners of H.LastGame))
(HT.SNAP "ph-game1")
(SETQ G1 H.LastGame)
(PH.Start PH.CurrentTable)
(DISMISS 4000)
(HT.CHECK "game 2 is on a fresh table" (AND (NEQ PH.CurrentTable T1) (NOT (OPENWP T1)) (OPENWP PH.CurrentTable)))
(HT.CHECK "game 2 is running" (PH.Running? PH.CurrentTable))
(SETQ PROC2 (PH.Running? PH.CurrentTable))
(HT.SNAP "ph-game2")
(PHT.HeartsWindows)
(PH.Exit PH.CurrentTable)
(DISMISS 1000)
(HT.CHECK "Exit stops the game process" (NOT (PROCESSP PROC2)))
(HT.CHECK "Exit closes every Hearts window" (NULL (PHT.HeartsWindows)))
(HT.CHECK "Exit deletes the Expert units" (AND NAME1 (NULL (GetObjectRec NAME1))))
(HT.SNAP "ph-after-exit")
(* "Closing the table window instead of Exit ends the session too.")
(SETQ T3 (PlayHearts (QUOTE (CLOWN CP CLOWN CP))))
(CLOSEW T3)
(HT.CHECK "closing the table closes the rest" (NULL (PHT.HeartsWindows)))
(* "The interactive path: (PlayHearts) with no arguments asks with menus and a name prompt.
    Script the answers by advising MENU and PROMPTFORWORD.")
(SETQ PHT.Answers (QUOTE (HP EP CP CLOWN NO NO YES)))
(ADVISE (QUOTE MENU) (QUOTE BEFORE) (QUOTE (RETURN (pop PHT.Answers))))
(ADVISE (QUOTE PROMPTFORWORD) (QUOTE BEFORE) (QUOTE (RETURN "Tester")))
(SETQ T4 (PlayHearts))
(UNADVISE (QUOTE MENU))
(UNADVISE (QUOTE PROMPTFORWORD))
(HT.CHECK "asked-for config" (WINDOWPROP T4 (QUOTE PH.Config)) (QUOTE (HP EP CP CLOWN)))
(HT.CHECK "human named from the prompt" (fetch Name of (CAR (WINDOWPROP T4 (QUOTE PH.Players)))) "Tester")
(HT.CHECK "Conservative thoughts on" ThinkFlag?)
(HT.CHECK "human window open" (MEMBER "Hearts Window for Tester" (PHT.HeartsWindows)))
(HT.SNAP "ph-asked")
(PH.Exit T4)
(HT.CHECK "and Exit cleans that up too" (NULL (PHT.HeartsWindows)))
